###
# Login
@hostname = localhost
@port = 8080
@host = {{hostname}}:{{port}}

# Credenciales válidas
###
POST http://localhost:8080/api/usuarios/registro
Content-Type: application/json

{
  "nombreUsuario": "admin",
  "contrasena": "password"
}
###
POST http://localhost:8080/api/usuarios/login
Content-Type: application/json

{
  "nombreUsuario": "admin",
  "contrasena": "password"
}